### ISSUE TITLE
importing common types for use in app/addon?

### ISSUE THREAD

**Issue by lougreenwood** [FortAwesome/ember-fontawesome#102]
Hello,

I'm using this addon and recently had a need to also use the font awesome types `@fortawesome/fontawesome-common-types`.

However, the common-types addon suggests the following:

> If you are trying to import types from this package we highly recommend you do the following instead as all types in this package are re-exported to the main fontawesome package.
> 
> your.ts
> ```
> import {
>   IconName
> } from `@fortawesome/fontawesome`
> ```

The problems I seem to face are:

* The `@fortawesome/fontawesome` package is not installed when using ember-font awesome, so if I do as the above suggests, I get a runtime error `TypeError: Cannot read property 'iconName' of undefined` and no types in my IDE.
* If I directly import from `@fortawesome/fontawesome-common-types` I *do* get types in my IDE, but I then get the following error when building my app:

```
Build Error (Bundler)

Can't resolve '@fortawesome/fontawesome-common-types' in '/path/to/my-addon'
```

So I wonder if there's any suggested way to consume the font awesome types when using ember-font awesome?

Thanks!

**Comment by jrjohnson** [comment]
Ember font awesome is designed to provide an easy path to getting the icons into your app, and probably doesn't cover your use case here. Instead I think you should use [ember-auto-import](https://github.com/ef4/ember-auto-import) and then you can install `@fortawesome/fontawesome` directly in your app and import the packages you need.
