### ISSUE TITLE
Readme example not working

### ISSUE THREAD

**Issue by maxwondercorn** [FortAwesome/ember-fontawesome#108]
I was creating a PR to document the new Ember angle bracket component syntax and found that this example in the readme does not render correctly

```
<span class="fa-layers fa-lg">
  {{fa-icon 'circle'}}
  {{fa-icon class='fa-inverse check' transform='shrink-6'}}
</span>
```

The circle renders, the check does not.  I though maybe the `fa-inverse` class should have been in a `<span></span>`  surrounding `{{fa-icon 'check'}}` but that doesn't work either.

Not that is should make a difference but I'm only using the pro icon sets

**Comment by st-h** [comment]
@maxwondercorn I think the issue is that the second `{{fa-icon ...}}` is missing the icon name `check`,  but is used to add a class. This seems to work (as long as your current color is not white):
```
<span class="fa-layers fa-lg">
  {{fa-icon 'circle'}}
  {{fa-icon 'check' class='fa-inverse' transform='shrink-6'}}
</span>
```

**Comment by maxwondercorn** [comment]
Thanks - that couldn't have been more obvious.  I'll fix the example in the PR I created for angle brackets
