### ISSUE TITLE
Duotone progress? 

### ISSUE THREAD

**Issue by robclancy** [FortAwesome/ember-fontawesome#114]
https://github.com/FortAwesome/ember-fontawesome/commit/ab3ec47b50627bb15692e6168afc23010488e852

It's been 2 months and things seem to be done privately so we can't see or know about anything?

**Comment by robmadole** [comment]
@robclancy we just haven't got the bandwidth yet to work on this. It's on the radar and we'll get to it as soon as we can.

**Comment by robclancy** [comment]
This is an open source library. It says it is in pre-release. Why not just put that branch on here so you can benefit from open source if people have time/motivation to help with getting this feature?

For us we will have a big update being started soon that won't be released for months so using a beta of something is fine. I think I'm going to override the component so that we can set "duo" as the prefix but have it go back to solid so that when this happens we can just benefit with all icons we want duo updated. But that's assuming that this will be done with `@prefix="duo"`?

**Comment by robmadole** [comment]
@robclancy not sure I understand. We haven't started a branch yet. Were you thinking that we did?

**Comment by robclancy** [comment]
The way I read this is that the duotones are in pre-release for this. Since when you added this the duotones were already released in font-awesome.

> Duotone icons are currently in pre-release and are coming soon to this component.

**Comment by robclancy** [comment]
I don't know what extra support is needed, I guess to be able to set colours for each tone? But if you include the duotone icons then it just works.
