### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by ShepherdHub** [FortAwesome/ember-fontawesome#116]
I ran the ember install command  

`$ ember install @fortawesome/ember-fontawesome`

And I received the following error. I'm not sure how to proceed.

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: 1
  - codeFrame: [undefined]
  - errorMessage: Command failed: yarn add --dev @fortawesome/ember-fontawesome --non-interactive
error Couldn't find package "@fortawesome/ember-fontawesome" on the "npm" registry.
```

Node: v12.10.0
NPM: 6.10.3
Yarn: 1.17.3

Ubuntu 18.04 on WSL

**Comment by jrjohnson** [comment]
@ShepherdHub I believe this was probably a temporary installation issue possible network related. Feel free to open again if you're still seeing it.
