### ISSUE TITLE
DEPRECATION: Use of `assign` has been deprecated. Please use `Object.assign` or the spread operator instead.

### ISSUE THREAD

**Issue by mkszepp** [FortAwesome/ember-fontawesome#189]
**Ember:** 4.0.x
**Ember Fontawesome:** 0.2.3

DEPRECATION: Use of `assign` has been deprecated. Please use `Object.assign` or the spread operator instead. [deprecation id: ember-polyfills.deprecate-assign] See https://deprecations.emberjs.com/v4.x/#toc_ember-polyfills-deprecate-assign for more details.

https://github.com/FortAwesome/ember-fontawesome/blob/8c0e215d92fac8fe7baa44bd4c208aa5e880b40c/addon/components/fa-icon.js#L4

https://github.com/FortAwesome/ember-fontawesome/blob/8c0e215d92fac8fe7baa44bd4c208aa5e880b40c/addon/components/fa-icon.js#L92

**Comment by jrjohnson** [comment]
Thanks @mkszepp, if you would be willing to create a pull request to make this change I'd be happy to merge it.

**Comment by mkszepp** [comment]
@jrjohnson pull request added

**Comment by GendelfLugansk** [comment]
@jrjohnson Hi. Do you have a plan to release a new version that includes this fix soon?

**Comment by jrjohnson** [comment]
Yes. Hopefully the changes for embroider support will land very soon and we'll get a release out with both. In the interim you can always silence deprecation warnings using [ember-cli-deprecation-workflow](https://github.com/mixonic/ember-cli-deprecation-workflow).

**Comment by jrjohnson** [comment]
`0.3.0` is out now with this fix.
