### ISSUE TITLE
Uncaught TypeError: Cannot read property 'commit' of null

### ISSUE THREAD

**Issue by mhluska** [FortAwesome/ember-fontawesome#20]
I upgraded from 0.0.11-1 to 0.0.12 and I've started seeing this error on a particular route of my app.

The full stack trace:

```
runtime.js:6407 Uncaught TypeError: Cannot read property 'commit' of null
    at Environment.commit (runtime.js:6407)
    at Environment.commit (environment.js:266)
    at InteractiveRenderer._renderRootsTransaction (renderer.js:359)
    at InteractiveRenderer._renderRoot (renderer.js:289)
    at InteractiveRenderer._appendDefinition (renderer.js:214)
    at InteractiveRenderer.appendOutletView (renderer.js:202)
    at invokeWithOnError (backburner.js:216)
    at Queue.flush (backburner.js:125)
    at DeferredActionQueues.flush (backburner.js:278)
    at Backburner.end (backburner.js:410)
```

Diff of dependencies:

```
-    "@fortawesome/ember-fontawesome": "0.0.11-1",
+    "@fortawesome/ember-fontawesome": "0.0.12",
     "@fortawesome/fontawesome-free-brands": "^5.1.0-3",
-    "@fortawesome/fontawesome-free-regular": "^5.1.0-3",
-    "@fortawesome/fontawesome-free-solid": "^5.1.0-3",
+    "@fortawesome/fontawesome-pro-light": "^5.0.8",
+    "@fortawesome/fontawesome-pro-regular": "^5.0.8",
+    "@fortawesome/fontawesome-pro-solid": "^5.0.8",
```

You can see I also upgraded to pro icons. Not sure if that has anything to do with it. It's not out of the question that this error is unrelated to this library. But I thought it's likely since it's the only dependency that changed.

**Comment by mlwilkerson** [comment]
Hey @mhluska. Thanks for using `ember-fontawesome`!

I'm not sure how `Environment.commit` is related to what we're doing with `ember-fontawesome`.
However, there are some significant differences between those `5.0.8` packages of icons and the `5.1.0-3` pre-release versions. Off the top of my head, how those differences might account for this error, but just know that they _are_ very different, I'd be interested to see what happens if you upgrade to `ember-fontawesome@0.0.12` , but keep your icon packs at `5.1.0-3`. It probably means you'd need to use the free ones for the purpose of the scenario. But if that's possible, it might help to isolate what's going on.

**Comment by mhluska** [comment]
@mlwilkerson I figured out the issue. It was completely unrelated to fontawesome. It was caused by a runtime error in a `didInsertElement` hook. Strange. Sorry for the distraction.

**Comment by tarponjargon** [comment]
@mhluska how did you debug that?  I am getting the same error when transitioning between two specific routes and I cannot find the source of it.  This is the only hit on google for the same error.  Any help appreciated.

**Comment by mhluska** [comment]
@tarponjargon oh man, I can't remember exactly at this point. I think it was related to modifying some state in a `didInsertElement` hook. What I did was set a breakpoint on error in Chrome and then slowly work up the error stack looking at local variables in the Ember source to get clues about what was causing it. I also looked at the diff of my unstaged changes and there were only a few candidates. Maybe you can go back a commit or two to figure out where the error started happening?

**Comment by tarponjargon** [comment]
@mhluska thanks for responding.  I finally figured it out.  I had two different components, both using ember-radio-button, that were using the same `radioId`.

**Comment by PritamBhanji08** [comment]
this error could be caused due to the third party component which we try to use but could not be found inside the vendor.js or bundle.js ( final merrged or build javascript)
