### ISSUE TITLE
Absolute path to package is presented in the build output assets

### ISSUE THREAD

**Issue by stevcooo** [FortAwesome/ember-fontawesome#212]
**Describe the bug**
When you install [`@fortawesome/ember-fontawesome": "^0.4.0"`](https://github.com/FortAwesome/ember-fontawesome/releases/tag/0.4.0) and do an `ember build --prod`, the output file `vendor....js` in `dist` folder contains the absolute path to another package (`ember-get-config`).

**Reproducible test case**
Here I've created a repo where the issue can be reproduced easily [fa-test](https://github.com/stevcooo/fa-test).  If you want you can directly examine the [vendor file](https://github.com/stevcooo/fa-test/blob/master/dist/assets/vendor-87505b021e6f74ea0408df494e7882fd.js#L5247).   
Or get the repo, and do  `npm install` and examine `vendor...js` file in `dist` folder, you should see an absolute path to one of the packages in your local machine.

**Expected behavior**
We want deterministic builds that are absolute-path invariant (i.e. the build output shouldn't depend on the machine or the location of the project in the file system). Sometimes we build on our local machine, but sometimes the build is done in some agent (CI/CD Azure for example). We want build outputs to be identical no matter the machine that they are built on.
This is a regression issue, it wasn't presented earlier [`@fortawesome/ember-fontawesome": "^0.2.3"`](https://github.com/FortAwesome/ember-fontawesome/releases/tag/0.2.3) version that we used.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 104.0.5112.81 (Official Build) (64-bit)

**Additional context**
Please check the [ReadMe](https://github.com/stevcooo/fa-test#readme) file for more instructions about this issue.

**Comment by jrjohnson** [comment]
Thanks for the report! That indeed looks like a bug. Please report this to [ember-get-config](https://github.com/mansona/ember-get-config) as I don't think it is a problem specific ember-fontawesom. If I'm wrong about this or not understanding how we could fix it here feel free to re-open this ticket here.

**Comment by stevcooo** [comment]
This issue is now resolved since it was originally caused by @embroider/macros, just use @embroider/macros >=1.9.0.
https://github.com/embroider-build/embroider/releases/tag/release-2022-10-06.0
