### ISSUE TITLE
Is this working with Emble3.0?

### ISSUE THREAD

**Issue by chenfanggm** [FortAwesome/ember-fontawesome#26]
I tried to use this, but errors are obvious.

**Comment by robmadole** [comment]
What errors are you getting? This is compatible with 3.0.

**Comment by bgentry** [comment]
Yes, it works fine with Ember 3.0. That's how I'm using it.

**Comment by mukk85** [comment]
I keep receiving:

Build Error (Rollup)

EEXIST: file already exists, mkdir '.../tmp/fontawesome-cache_path-eNyhPZs7.tmp/node_modules/'

**Comment by robmadole** [comment]
Ah @chenfanggm this is #24. Closing as dupe
