### ISSUE TITLE
Latest icons not available

### ISSUE THREAD

**Issue by bgentry** [FortAwesome/ember-fontawesome#27]
Following up on [this comment](https://github.com/FortAwesome/ember-fontawesome/pull/25#issuecomment-374799573) from @robmadole:

> Regarding the missing icons: our `5.1.0` release hasn't been caught up with the latest icons yet. We have a `development` branch that we are working out of and we haven't merged `master` in for a bit as we work through the big refactor. This will happen soon.

So the newest icons are not available, including the logistics and medical categories.

Opening this issue to track it in case others run into it.

**Comment by robmadole** [comment]
@bgentry I've released 5.1.0-5 which includes the newer icons. We have a better process now for keeping all this up-to-date ;)

**Comment by bgentry** [comment]
@robmadole glorious, they look great 😍

**Comment by robmadole** [comment]
My pleasure...thank you for spurring a spirited Git and process conversation between @mlwilkerson and myself 😃
