### ISSUE TITLE
FastBoot

### ISSUE THREAD

**Issue by mhluska** [FortAwesome/ember-fontawesome#30]
This seems to inject some styles in a `<style>` tag at browser render time that isn't available during FastBoot render so the icon sizes change once the browser takes over. Will there be support for FastBoot?

**Comment by mlwilkerson** [comment]
Looks like a case for using this technique suggested for server-side rendering in general:
https://fontawesome.com/how-to-use/server-side-rendering

@mhluska Could you try an equivalent configuration with FastBoot and report back on how that goes? 

I expect that to solve the problem, and then we could consider whether we want to highlight for other Ember users just by providing a configuration guide on this component's readme, or if we want try and do something fancier.

**Comment by jrjohnson** [comment]
This is going to be a problem for fastboot and for static icon generation where `fontawesome.icon()` is called at build time and there is no `DOM` to insert styles into. I think we need to insert the styles into `vendor.css` at build time and turn off `autoAddCss`  to solve both of these issues. I will take a stab at a fix unless there are objections.

**Comment by mlwilkerson** [comment]
Sounds good to me.
