### ISSUE TITLE
Drop support for imported icon object

### ISSUE THREAD

**Issue by jrjohnson** [FortAwesome/ember-fontawesome#32]
The syntax:
```javasccript
import Controller from '@ember/controller'
import { faCoffee } from '@fortawesome/fontawesome-free-solid'

export default Controller.extend({
  faCoffee,
});
```

```handlebars
{{fa-icon faCoffee}}
```

Is pretty foreign in my ember experience and leads to confusion like #29. I think supporting `{{fa-icon 'coffee'}}` and 

```
import Controller from '@ember/controller'

export default Controller.extend({
  iconName: 'coffee',
});
```

```handlebars
{{fa-icon iconName}}
```

is sufficient, easier to document, and less confusing.

**Comment by bgentry** [comment]
Isn't that last suggestion going to result in linting errors due to an unused `faCoffee` import?

**Comment by jrjohnson** [comment]
Thanks @bgentry. Copy paste was not my friend. Fixed that.

**Comment by robmadole** [comment]
I'm :+1: for this if it's more familiar to Ember devs.

**Comment by bgentry** [comment]
This seems more logical to me. Only one syntax to remember, no imports necessary beyond the build config.

If there’s no real reason somebody would need access to the icon JS object then 👍🏻

**Comment by mlwilkerson** [comment]
@jrjohnson I'm good with dropping support for using the JS icon object too. Though if we do that, I wonder whether even the `iconName` part of your example would be necessary. I'm not sure why it would need to be there.

So maybe that controller code could be entirely eliminated and just always use the icon's name as a string in the template?

```javascript
{{fa-icon 'coffee'}}
```

If not, what advantage is there to having the extra layer of redirection through the controller's setup of `iconName`?

**Comment by tcjr** [comment]
> If not, what advantage is there to having the extra layer of redirection through the controller's setup of iconName?

It does not need to be there in this case.  I believe the main use case for this is being able to set the icon at runtime without putting that logic in the template.  Something like this:
```
  mailIcon: computed('isUnread', () => {
    return this.get('isUnread') ? 'envelope' : 'envelope-open';
  }
```
and
```
  {{fa-icon mailIcon}}
```

**Comment by mlwilkerson** [comment]
Oh, perfect. That makes sense. Thanks for shedding some light on that, @tcjr.
