### ISSUE TITLE
Bound values for spin and pulse are not working

### ISSUE THREAD

**Issue by tcjr** [FortAwesome/ember-fontawesome#33]
Bound values for `spin` and `pulse` do not appear to work correctly.  Once the spin is turned on, it can never be turned off.

I created a simple use case in the test application:

```
{{fa-icon 'sync' spin=isSpinning}} {{input type="checkbox" checked=isSpinning}} Spin it
```

When you set `isSpinning` to true, the icon correctly begins to spin.  But toggling it to false, does not stop the spinning.  That is, the `fa-spin` class is never removed.

https://github.com/tcjr/ember-fontawesome/commit/67aea5ced46894ce7db3756a94753f1788c702b9

**Comment by robmadole** [comment]
Can you please share an example that reproduces the issue you are seeing?

What we'd recommend is using a site like **[codepen.io](https://codepen.io), [jsfiddle.net](https://jsfiddle.net), [jsbin.com](https://jsbin.com), or [codesandbox.io](https://codesandbox.io)** (which is great if you are dealing with NPM packages).

**Comment by robmadole** [comment]
@tcjr sorry! Mike just pointed out that you have a test case in your fork. My bad. We'll get this on the list.

**Comment by bgentry** [comment]
@robmadole on a related note, one thing that I've really liked in other projects is when the readme has a link to an [Ember Twiddle](https://ember-twiddle.com) that could quickly be forked to set up a bug reproduction. Here's [an example from ember-concurrency](https://ember-twiddle.com/b2b0c016f4df24261381487b60c707f3?numColumns=2&openFiles=templates.application.hbs%2Ctemplates.application.hbs). This might help ensure better quality bug reports.

Corresponding readme section [here](https://github.com/machty/ember-concurrency#problems).

**Comment by mlwilkerson** [comment]
@bgentry Ooh...what a great idea!

**Comment by tcjr** [comment]
@robmadole @bgentry I would much rather use Ember Twiddle instead of forking.  

I spent about 20 minutes this morning trying to get Ember Twiddle to work with this project.  As soon as I added `"@fortawesome/ember-fontawesome"` to the `addons` section of the `twiddle.json` file, it goes into a building state and never comes out.  

I also tried adding it to `dependencies`.  In that case, the build completes, but in the console I see `Compile Error: fa-icon is not a helper`, which is not a surprise, I suppose.

It could be that Ember Twiddle doesn't support the new `@` npm business?  Just a guess.

If somebody has a minimal working example with this project, maybe you can show me what I'm doing wrong:  [ember-fontawesome example twiddle](https://ember-twiddle.com/fed1d98d42ff9fb23471b2645815c23e?numColumns=2&openFiles=templates.application.hbs%2Ctwiddle.json)
