### ISSUE TITLE
Add default prefix configuration option

### ISSUE THREAD

**Issue by nickschot** [FortAwesome/ember-fontawesome#35]
If you want to use a set other than free solid, you have to add the prefix to every icon use. An addon configuration option to change the default prefix would make using the other icons sets (or changing between them) much easier.

**Comment by mlwilkerson** [comment]
@robmadole I wonder, if this were desirable for the Ember component, might it be desirable elsewhere too? Possibly at the level of the core API?

Currently, we _define_ `fas` to be the default prefix at the API level:
> ...The new default is the `fas` solid style and the `fab` style for brands.
> [fontawesome.com API doc](https://fontawesome.com/how-to-use/svg-with-js)

**Comment by bgentry** [comment]
@mlwilkerson it does seem odd to make the default more painful for your pro customers that want to use pro icons :)

**Comment by mlwilkerson** [comment]
@bgentry Do you mean that a Pro customer might well prefer to have `fal` (Light style, Pro-only), for example, be the default?

**Comment by nickschot** [comment]
The way you'd normally configure this for Ember is in the environment configuration which you can access from the addon at runtime (with i.e. `ember-get-config`). Adding a `defaultPrefix` which defaults to `fas` would be enough. I don't know how you'd handle this globally/in your other addons.

Main reason for me was indeed that it is very painful to switch between styles right now as you'd have to update all component usages instead of changing the single configuration option.

**Comment by mlwilkerson** [comment]
@nickschot it sounds like (at least part of) your use case is "make it easier to switch from one style to another and have all of my icons move over to that other style". Did I hear you right?

If so, then there's another thing to be concerned about here: In many cases, switching styles for the same `iconName` requires a move from a Free icon package to a Pro icon package. So a Free-only customer who tries to make that switch would experience a whole bunch of broken icons all of a sudden. At the very least, I think we'd need to provide a helpful warning or something. And I wonder whether switching styles wholesale like that is even a use case that needs to be enabled.

I'm just kicking the tires on the proposal here, not trying to shoot anything down.

**Comment by bgentry** [comment]
> @bgentry Do you mean that a Pro customer might well prefer to have fal (Light style, Pro-only), for example, be the default?

Yep, that is exactly my situation. When I switched to using light icons, I had to go add `prefix="fal"` to every single `{{fa-icon}}` invocation. I probably could have overridden the component to get the same effect but didn't feel comfortable doing that at this early stage.

I think that the default style should be configurable so I can essentially say "if I don't provide a prefix, assume I want the light ones".

**Comment by nickschot** [comment]
@mlwilkerson Kicking tires is good! Exactly the reason why I first created the issue and not the PR ;-). Switching styles while working on the design of the app is good I think. 

Otherwise, what @bgentry just said in the comment above also applies and is the more general quality of life improvement imo.
