### ISSUE TITLE
bring back fa-icon helper/component which accepts fa icon/object

### ISSUE THREAD

**Issue by st-h** [FortAwesome/ember-fontawesome#44]
passing an fa icon to the fa-icon helper seems to have been deprecated
```
DEPRECATION: Passing an icon object is no longer supported, use the icon name as a string instead ({{fa-icon 'plus-circle'}}).  [deprecation id: ember-fontawesome-no-object]
```
Please bring back this functionality, as removing it makes it unnecessarily difficult to pass an icon to a nested component, as it is no longer possible to correctly reference a single icon without passing multiple parameters. For instance one could previously do:

```
{{my-input-component fa=faCircle value=...}}
```

One could import the correct icon in a controller or component and simply pass it to the component, where we could simple use it:

my-input-component.hbs:
```
<label>{{fa-icon fa}}</label>
<input></input>
```

now we need to pass every single information to the component in order to identify an icon correctly. for instance:
```
{{my-input-component fa-icon="fa-circle" fa-icon="fas"  value=...}}
```

Please bring back a way to specify an icon by using a single parameter. The deprecation, even though it might help internally, only complicates things for the people using it.

**Comment by jrjohnson** [comment]
Sorry @st-h that's on me. My goal in #32 was to limit the API surface to make this addon easier to use. I will remove the deprecation warning and modify the documentation instead.

**Comment by st-h** [comment]
well, that is interesting to follow... I'll add my thoughts below:

> Is pretty foreign in my ember experience 

Yes, it kind of is in some ways. Much like using the layout property when building components. Feels a little strange, but yet it is part of ember.

> and leads to confusion like #29.

my first thought here would have been that the root issue is that we need to import fa stuff, using the fa prefix. I actually really dislike that as it never seems to be in line with the list of icons on the fa website. They call icons like `plus-circle`. Whereas the actual class name is `fa-plus-circle`. Now what is the correct import? `plus-circle`, `fa-plus-circle`, `faPlusCircle`, `FaPlusCircle`, `plusCircle` or something different? and what do we need to configure in the build config? However, I have seen there already is a PR open to simplify things regarding that, which I think would be great.

and to add more confusing things.... The root of this issue here is, that we no longer have a simple way to uniquely reference icons in fa5. If we could have a way to specify an icon by using a simple string, I would be totally happy with the change to remove support for objects. Like if we could just use something like `{{fa-icon 'fas/circle-plus'}}` or `{{fa-icon 'fas-circle-plus'}}`. However, the way things currently are, I fear this will only make things more complicated, as this again is not in line with what is currently specified on the fa website and will just be another framework dependent exception.
