### ISSUE TITLE
Publish release tags on github?

### ISSUE THREAD

**Issue by bgentry** [FortAwesome/ember-fontawesome#5]
According to [the npm page](https://www.npmjs.com/package/@fortawesome/ember-fontawesome), there have been 3 releases of this package. However, [the Github page](https://github.com/FortAwesome/ember-fontawesome/releases) shows none.

Can you publish release tags for this addon each time you publish a release on npm (as is standard practice)? Thanks :pray:

**Comment by robmadole** [comment]
Yep, good reminder @bgentry. Those are pre-releases so we'll get GitHub reflecting those when we hit full releases.

**Comment by mlwilkerson** [comment]
Yeah, my intent has been to publish only pre-releases at this time, before the first "real" release. The fact that any of them ever showed up as releases was accidental. That'll all be cleaned up soon.

**Comment by bgentry** [comment]
Yeah that makes sense, though even for pre-releases it's helpful to see what's changed between versions. See [ember-cli](https://github.com/ember-cli/ember-cli/releases) for an example.

Looking forward to trying this out!

**Comment by robmadole** [comment]
@bgentry yes absolutely agreed. We are still working on process for how we handle pre-releases and how we manage these projects. Everything has been a pretty loose. @mlwilkerson and I will get more "professional" about this as soon as we can.

**Comment by jrjohnson** [comment]
Ya'll are doing awesome! Release management is the secret third hard problem in computer science! 😄

**Comment by mlwilkerson** [comment]
Thanks, @jrjohnson. It's not a secret any more :wink:
