### ISSUE TITLE
Update icon packages?

### ISSUE THREAD

**Issue by jrjohnson** [FortAwesome/ember-fontawesome#56]
It looks to me like published icon packages have been reduced from 
```
@fortawesome/free-brands-svg-icons
@fortawesome/free-solid-svg-icons
@fortawesome/free-regular-svg-icons
@fortawesome/pro-solid-svg-icons 
@fortawesome/pro-regular-svg-icons 
@fortawesome/pro-light-svg-icons 
```

to just 

```
@fortawesome/free-icons
@fortawesome/pro-icons 
```

Is that correct? If so we should update the README and the imports for static build time icons at https://github.com/FortAwesome/ember-fontawesome/blob/master/lib/fontawesome-helpers.js#L19.

**Comment by robmadole** [comment]
Hey @jrjohnson ! No, we still have the packages split out. We have _not_ published `free-icons` or `pro-icons`. What made you think that we changed this?

**Comment by jrjohnson** [comment]
Oh ok, the docs at https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-free were what gave me this idea.

**Comment by robmadole** [comment]
@jrjohnson gotcha. yeah that new `fontawesome-free` package is basically a clone of what we put on the Free CDN.
