### ISSUE TITLE
Icon name with kebab case (Ex. fas fa-users-cog)

### ISSUE THREAD

**Issue by dyennam** [FortAwesome/ember-fontawesome#59]
Is there a list of icons that are yet to be available in ember-fontawesome
https://fontawesome.com/icons/users-cog?style=solid (This icon is not yet supported)

Tried the below two methods but no luck.
`  {{fa-icon "users-cog" prefix='fas' size='2' color='white' }}`
`  {{fa-icon "fas fa-users-cog" size='2' color='white'}}`
Or are the above icons not supported yet.
`  fontawesome: {
      icons: {
        'free-brands-svg-icons': 'all',
        'free-regular-svg-icons': 'all',
        'free-solid-svg-icons': 'all'
      }
    }`
I have the above config for ember-cli-build.js

**Comment by robmadole** [comment]
@dyennam please provide a reproducible example and we'll take a look.

**Comment by jrjohnson** [comment]
@dyennam going to close since we haven't heard back from you.
