### ISSUE TITLE
Simple {{fa-icon "coffee"}} not working in IE11 because of Object.assign in didReceiveAttrs

### ISSUE THREAD

**Issue by samcic** [FortAwesome/ember-fontawesome#61]
Trying to render a simple `{{fa-icon "coffee"}}` on IE11 gives an error:

> Object doesn't support property or method 'assign'

The problem is the following line in the `didReceiveAttrs` function of `addon/components/fa-icon.js`:

```
const o = Object.assign({},
      classes,
      transform,
      mask,
      {symbol: symbol}
    )
```

[IE11 doesn't support Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign). 

Adding IE11 to my targets.js file also doesn't help here.

From what I can tell, FA5 [supports IE11](https://fontawesome.com/how-to-use/on-the-web/other-topics/browser-support).

Ember also [officially supports IE11](https://github.com/kaliber5/ember-bootstrap/issues/454) unless I'm mistaken.

I couldn't see any comments about limited browser support for this add-on. Is this hence a bug or is IE11 not supported by this add-on?

**Comment by scottwernervt** [comment]
A possible solution would be to use `Ember.assign({}, ...)`.

https://www.emberjs.com/api/ember/2.18/functions/@ember%2Fpolyfills/assign.

**Comment by samcic** [comment]
So I'm a bit confused about how to make this contribution. I tried to follow the contribution guidelines but got stuck at the `npm publish` stage because of a:

```
Failed PUT 404
npm ERR! code E404
npm ERR! 404 Not found : @fortawesome/ember-fontawesome
npm ERR! 404
npm ERR! 404  '@fortawesome/ember-fontawesome' is not in the npm registry.
```

So I created a PR from a forked repository instead. Was this a mistake, and if so how should I make this contribution?

**Comment by jrjohnson** [comment]
@samcic you won't be able to publish the release. The PR should only be the change to Ember.Assign and then let the FA maintainers handle the rest.
