### ISSUE TITLE
Build time component doesn't use defaultPrefix

### ISSUE THREAD

**Issue by josemarluedke** [FortAwesome/ember-fontawesome#65]
I'm getting the following warning when having `enableExperimentalBuildTimeTransform` enabled.

```WARNING: @fortawesome/ember-fontawesome: Unable to load icon 'search' with prefix 'fas'.```

I have my `defaultPrefix` set to `fal`, it works fine at runtime, but it complains in build time.

Note, I do have the `search` icon in my build.

**Comment by jrjohnson** [comment]
Yes. I was working on this when I ran into #57. I've been on vacation for a couple of weeks, but I was planing to take a look at this when I get back.
