### ISSUE TITLE
missing icons render a tall, skinny svg element

### ISSUE THREAD

**Issue by bgentry** [FortAwesome/ember-fontawesome#7]
<img width="210" alt="screen shot 2018-02-20 at 4 59 45 pm" src="https://user-images.githubusercontent.com/114033/36457571-881dc6c0-165f-11e8-9559-0bb868d55a4a.png">

I believe this is because the svg has no viewbox? The other icons have a `viewbox="0 0 512 512"`. Ideally a missing icon wouldn't disrupt the flow of the page like this.

Edit: actually it's the `.svg-inline--fa` class where a 1em height comes from. So maybe a missing SVG should have some kind of default classes?

**Comment by mlwilkerson** [comment]
Thanks for catching that, @bgentry. Yes, I've wondered what would be the preferred "missing icon" behavior. I think I plug in the same "missing icon" icon that our mutation observer uses when it finds something like `<i class="fas fa-xyz"></i>` that it doesn't recognize. So the size would end up being the same as the intended icon, but would visually indicate a problem.

Does that sound appropriate to you?

**Comment by bgentry** [comment]
To me the most logical thing if the icon is missing is to log an error (in dev) and just render empty space in place of the icon. Is that what you're suggesting?

Otherwise some sort of default icon is at least much better than the current behavior.

**Comment by jrjohnson** [comment]
IIRC correctly from my testing a few months ago a missing icon renders as something specific in FA5. It was easy to spot visually.  Is that what the one from the mutation observer you are talking about @mlwilkerson? I don't hate the missing space idea, but I remember really liking the special missing icon.

**Comment by mlwilkerson** [comment]
Yes, @jrjohnson when using the `autoReplaceSvg` functionality, where you place `<i>` tags and let our code pick those up and translate them into `<svg>`s, missing icons look fancy, like this:
https://jsfiddle.net/mwilkerson/hpw53Lzb/2/

So there's precedent there for showing that missing icon.

That was my initial suggestion above to @bgentry, to show the same "missing icon" icon. The alternative would be to leave it blank in the page and just log a message to the console.

I don't have a really strong preference here myself, and I could see good reason to go either way.

But we definitely don't want the current behavior. So I'll put in a fix for that. For now, I'll leave it blank and log to the console.

**Comment by bgentry** [comment]
I think that either way you should keep the console warnings (outside prod anyway). They're a helpful reminder that might help some missing icons get noticed and make it easier for devs to know when they've made a mistake.

I'm indifferent as to whether the "missing icon" is shown vs. just blank space.
