### ISSUE TITLE
How do I use CSS Pseudo Elements?

### ISSUE THREAD

**Issue by erichonkanen** [FortAwesome/ember-fontawesome#79]
I tried following the instructions at https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements, but I am not able to get css pseudo elements working so far when using FA5 Pro. The element renders an empty box:
![image](https://user-images.githubusercontent.com/230757/48305798-30f87380-e4e6-11e8-8bda-37db76fd9f95.png)

Is there a configuration to enable this?
```
    &::before {
      font-family: 'Font Awesome 5 Pro';
      font-weight: 300;
      content: "\f078";
    }
```

**Comment by robmadole** [comment]
@erichonkanen the `ember-fontawesome` project uses the newer SVG implementation. If you need pseudo-element support you should probably switch to the webfonts with CSS version of Font Awesome and not use this project.
