### ISSUE TITLE
How can we attach events or actions to the icons?

### ISSUE THREAD

**Issue by JayasreeVeliyath** [FortAwesome/ember-fontawesome#86]
I have been using font-awesome in my Ember app like so.

`.times-tag{`
`color: '#FF0000'`
`}`
`
<i class="fa fa-times times-tag" onClick={{action 'deleteTag' item.id}} aria-hidden="true"></i>
`
How can we do the same with ember-fontawesome?

I tried
`{{fa-icon 'fa-times' 'times-tag'}`

Neither the 'times-tag' styling class is applied nor 'aria-hidden' attribute is attached.And there seems to be no reference in the documentation on how to add actions/events.

**Comment by st-h** [comment]
@JayasreeVeliyath you should be able to apply classes in the following way:
`{{fa-icon 'plus' class="times-tag"}}`

regarding actions, I think there are two ways to achieve this:

as fa-icon is essentially just a component, you can use the components events as listed [here](https://emberjs.com/api/ember/release/classes/Component): 
`{{fa-icon 'user' click=(action 'hello')}}`
However, I think there are two drawbacks using this method:
- in case the add-on makes use of an event, that you override this way, it could break the add-on
- this does not go well with accessibility, as an `<i>` element usually isn't expected to be clickable, so you would need to take care of this as well.

I think the better option is to wrap your icons with something that is designed to handle interactivity, like a button:
```
<button {{action 'sayHello'}}>
  {{fa-icon 'user'}}
</button>
```

Hope that helps.
