### ISSUE TITLE
'faPencilAlt' is not exported

### ISSUE THREAD

**Issue by Redsandro** [FortAwesome/ember-fontawesome#99]
```
$ ember install @fortawesome/ember-fontawesome
npm: Installed @fortawesome/ember-fontawesome
installing ember-fontawesome
Installed addon package.

$ npm i --save-dev @fortawesome/free-regular-svg-icons
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @fortawesome/free-regular-svg-icons@5.7.2
added 1 package from 6 contributors and audited 132981 packages in 12.653s
found 0 vulnerabilities
```

```
ember s
```

> Build Error (free-regular-svg-icons-rollup)
> 
> 'faPencilAlt' is not exported by node_modules/@fortawesome/free-regular-svg-icons/index.es.js

Ember 3.8

**Comment by Redsandro** [comment]
### Update

This is only when defining a subsection of icons in `environment.js`:

```
		fontawesome: {
			defaultPrefix: 'far',
			icons: {
				'free-regular-svg-icons': [
					// ...
				]
			}
		},
```

Commenting that out and it builds fine.

Am I doing this wrong? It is documented in `README.md`.

**Comment by allthesignals** [comment]
Did you ever figure out the source of this? I'm seeing something similar:

`'faBacon' is not exported by node_modules/@fortawesome/free-solid-svg-icons/index.es.js`

This is insanity. How do I troubleshoot this? 

My guess is it has to do with package versions:
```
    "@fortawesome/ember-fontawesome": "^0.1.6",
    "@fortawesome/free-regular-svg-icons": "^5.3.1",
    "@fortawesome/free-solid-svg-icons": "^5.3.1",
```

Maybe the semver downstream of ember-fontawesome doesn't jibe with the other two fortawesome packages? But how do I figure out what versions go with which?

**Comment by st-h** [comment]
@Redsandro i think you are seeing this because pencil-alt is a pro regular, or free solid icon. Not a free regular icon. I was close to banging my had against a wall a few times myself until I found the right package to use. Hope that helps though..

**Comment by st-h** [comment]
@allthesignals probably the installed packages are too old and just do not contain the bacon? Just a guess, but I am on 5.7.2 and bacon works fine with free solid.

**Comment by allthesignals** [comment]
Confirmed - the bacon was missing in those older versions. Bumping the versions included the bacon and eliminated the error. We are now able to import the bacon.

**Comment by jrjohnson** [comment]
Closing as this seems to be a dependency installation issue.
